Create AttributeError: 'Vector' object has no attribute 'append'
I'm trying to build a Vector() class. Now it can calculate addition and subtraction between Vectors.
-What I learnt:
  The append() method adds an item to the end of a list. If I want to append sth. to my Vector(), I need to define this method first.
-My question:
  1. This is too tedious, may anyone simplify it?
  2. Adding other vector calculations to it.